### ISSUE TITLE
client.py中ZhihuClient验证码部分有点错误

### ISSUE THREAD

**Issue by ghost** [dongweiming/weapp-zhihulive#1]
[代码链接](https://github.com/dongweiming/weapp-zhihulive/blob/master/Server/client.py#LC109)，因为api登录大部分时候`self.need_captcha()`不需要验证码会返回False，所以可能没遇到，`ZhihuClient`类中并没有给出`self.get_captcha()`的实现以及设置`CAPTCHA_FILE`。

**Comment by dongweiming** [comment]
@ormsf 嗯 我没遇到过需要验证码的场景，这部分的逻辑直接抄袭的 https://github.com/7sDream/zhihu-oauth/blob/master/zhihu_oauth/client.py#L80

如果你遇到了，可以修改一下 来提PR欧

**Comment by lucy1994lucy** [comment]
您好，请问有后端吗？还有，有数据库的类图设计之类的嘛？感谢感谢

**Comment by dongweiming** [comment]
@lucy1994lucy 没有，抱歉
