### ISSUE TITLE
crawl.py中fetch会陷入死循环

### ISSUE THREAD

**Issue by ghost** [dongweiming/weapp-zhihulive#2]
[代码链接](https://github.com/dongweiming/weapp-zhihulive/blob/master/Server/crawl.py#LC180)

```python
    async def fetch(self, url, max_redirect):
        ...
        try:
            ...
            if next_url is not None:
                self.add_url(next_url, max_redirect)
            else:
                for type in self.__stopped:
                    if type in url:
                        self.__stopped[type] = True
        finally:
            response.release()
```

知乎api的设计中，next_url永远都不会返回None，可以试一下https://api.zhihu.com/lives/ended?purchasable=0&limit=10&offset=10000000000

这样会导致self.__stopped[type]永远都是False，然后在work中会源源不断的往queue添加url，永远不会退出，crawl()会阻塞在`await self.q.join()`，work不会cancel：

```python
    async def work(self):
        try:
            while 1:
                url, max_redirect = await self.q.get()
                if url in self.seen_urls:
                    type = url.split('/')[-1].split('?')[0]
                    if not self.__stopped[type]:
                        self.add_url(get_next_url(url), max_redirect)
                await self.fetch(url, max_redirect)
                self.q.task_done()
                asyncio.sleep(1)
        except asyncio.CancelledError:
            pass
```

而且`self.__stopped = {}.fromkeys(['ended', 'ongoing', 'posts'], False)`，**好像**api只有ended和outgoing两种类型？

**Comment by dongweiming** [comment]
@ormsf 不会到10000000000，每次都会检查有下一页才添加这个url，这个`if next_url is not None`的逻辑在https://github.com/dongweiming/weapp-zhihulive/blob/master/Server/crawl.py#L191 并不是直接return没有数据的结果: 空列表

我本地跑一直是正常的呢，要不然我也不会把代码推上来。

posts是抓取官方Live专栏 https://zhuanlan.zhihu.com/api/columns/zhihulive/posts?limit=20&offset=20 中的地址中的posts

**Comment by ghost** [comment]
@dongweiming 确实是我弄错了，crawl.py中__parse_link__下有is_end的检查：
```python
            if not paging['is_end']:
                next_url = paging['next']
                return paging['next']
```

**Comment by dongweiming** [comment]
@ormsf 是的
