### ISSUE TITLE
crawl.py出错， 请问ES怎么配置？

### ISSUE THREAD

**Issue by ekgg** [dongweiming/weapp-zhihulive#9]
`python crawl.py 
PUT http://localhost:9200/live130 [status:400 request:0.008s]
Traceback (most recent call last):
  File "crawl.py", line 268, in <module>
    loop.run_until_complete(live_init())
  File "./Server/models/live.py", line 171, in init
    await Live.init()
    
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Custom Analyzer [ik_analyzer] failed to find tokenizer under name [ik_max_word]')
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1047e4128>`

环境： Mac, Python3.6.5,  es三个版本2.4.6/ 5.6.2 / 6.2.2 都试过，
脚本运行都出错，创建index失败

本地搭建的es是可以运行的，head插件可以正常访问es.

**Comment by ekgg** [comment]
翻了一下你的专栏，才发现需要 分词插件，安装了elasticsearch-analysis-ik就可以运行了。

**Comment by dongweiming** [comment]
O(∩_∩)O
